"""Verilator model sidecar public package."""

from .coverage import (
    COVERAGE_CONTRACT_SURFACE,
    COVERAGE_ORACLE_SURFACE,
    CoverageMappingError,
    build_toggle_coverage_mapping,
    coverage_region_contracts,
    validate_coverage_mapping,
)

from .boundary_benchmark import (
    RTL_BOUNDARY_ADJUDICATION_SURFACE,
    RTL_BOUNDARY_BENCHMARK_SCHEMA_VERSION,
    RTL_BOUNDARY_EVIDENCE_BUNDLE_SURFACE,
    RTL_BOUNDARY_EXPERIMENT_CONTRACT_SURFACE,
    RTL_BOUNDARY_SEMANTIC_MANIFEST_SURFACE,
    BoundaryBenchmarkError,
    adjudicate_boundary_benchmark,
)

from .boundary_report import (
    RTL_BOUNDARY_PIPELINE_RESULT_SURFACE,
    RTL_BOUNDARY_PLOT_PAYLOAD_SURFACE,
    RTL_BOUNDARY_REPORT_BUNDLE_SURFACE,
    RTL_BOUNDARY_REPORT_VALIDATION_SURFACE,
    build_boundary_report_bundle,
    validate_boundary_report_bundle,
)

from .effects import (
    EFFECT_CONTRACT_SURFACE,
    EFFECT_OBSERVATION_SURFACE,
    EFFECT_ORACLE_SURFACE,
    EvalEffectError,
    classify_eval_effects,
    validate_effect_contract,
    validate_eval_effects,
    write_eval_effects,
)

from .physical import (
    LAYOUT_OBSERVATION_SURFACE,
    PhysicalProbeError,
    probe_physical_layout,
    validate_layout_observation,
    write_layout_observation,
)

from .opentitan_evidence import (
    OPENTITAN_ADJUDICATION_RUN_SPEC_REPORT_SURFACE,
    OPENTITAN_ADJUDICATION_RUN_SPEC_SURFACE,
    OPENTITAN_ADJUDICATION_SURFACE,
    OPENTITAN_ADJUDICATION_SUMMARY_SURFACE,
    OPENTITAN_ADJUDICATION_SUMMARY_VALIDATION_REPORT_SURFACE,
    OPENTITAN_ADJUDICATION_VALIDATION_REPORT_SURFACE,
    OPENTITAN_EVIDENCE_BUNDLE_SURFACE,
    OPENTITAN_EVIDENCE_SCHEMA_VERSION,
    OPENTITAN_SEMANTIC_MANIFEST_SURFACE,
    OPENTITAN_TARGET_CONTRACT_SURFACE,
    OPENTITAN_TARGET_CONTRACT_REPORT_SURFACE,
    OpenTitanEvidenceError,
    adjudication_input_error,
    adjudicate_external_evidence,
    file_sha256,
    format_adjudication_report,
    format_adjudication_summary_report,
    format_output_validation_report,
    format_target_contract_report,
    read_strict_json_object,
    summarize_adjudications,
    validate_adjudication_document,
    validate_adjudication_run_spec,
    validate_adjudication_summary_document,
    validate_target_contract_document,
    write_json_atomic,
    write_text_atomic,
)

from .sweep_boundary import (
    RTL_BOUNDARY_ANALYSIS_SURFACE,
    RTL_BOUNDARY_GROUND_TRUTH_SURFACE,
    RTL_BOUNDARY_POLICY_ANALYSIS_SURFACE,
    RTL_BOUNDARY_POLICY_TRIAL_SURFACE,
    RTL_BOUNDARY_SCHEMA_VERSION,
    RTL_BOUNDARY_SWEEP_ENUMERATION_SURFACE,
    RTL_BOUNDARY_SWEEP_SPACE_SURFACE,
    SweepBoundaryError,
    analyze_boundary_ground_truth,
    analyze_boundary_policy_trial,
    enumerate_sweep_space,
    reconstruct_boundary_prediction,
    select_boundary_points,
)

from .native import (
    NATIVE_CHECKPOINT_SCHEMA_VERSION,
    NATIVE_CHECKPOINT_SURFACE,
    NATIVE_MANIFEST_SCHEMA_VERSION,
    NATIVE_MANIFEST_SURFACE,
    NATIVE_VERIFICATION_SCHEMA_VERSION,
    NATIVE_VERIFICATION_SURFACE,
    NativeManifestError,
    project_native_checkpoint,
    validate_native_checkpoint_manifest,
    validate_native_manifest,
    write_native_checkpoint,
    verify_native_adapter,
    write_native_verification,
)

from .native_eval import (
    NATIVE_EVAL_PROJECTION_SCHEMA_VERSION,
    NATIVE_EVAL_PROJECTION_SURFACE,
    extract_native_eval_closure,
)

from .semantic import (
    MANIFEST_SCHEMA_VERSION,
    MANIFEST_SURFACE,
    SidecarError,
    analyze_manifest,
    capture_manifest,
    extract_semantic_projection,
    resolve_physical_bindings,
    validate_manifest,
    verify_adapter_semantics,
    write_manifest,
)

__all__ = [
    "COVERAGE_CONTRACT_SURFACE",
    "COVERAGE_ORACLE_SURFACE",
    "EFFECT_CONTRACT_SURFACE",
    "EFFECT_OBSERVATION_SURFACE",
    "EFFECT_ORACLE_SURFACE",
    "MANIFEST_SCHEMA_VERSION",
    "MANIFEST_SURFACE",
    "LAYOUT_OBSERVATION_SURFACE",
    "NATIVE_CHECKPOINT_SCHEMA_VERSION",
    "NATIVE_CHECKPOINT_SURFACE",
    "NATIVE_EVAL_PROJECTION_SCHEMA_VERSION",
    "NATIVE_EVAL_PROJECTION_SURFACE",
    "NATIVE_MANIFEST_SCHEMA_VERSION",
    "NATIVE_MANIFEST_SURFACE",
    "NATIVE_VERIFICATION_SCHEMA_VERSION",
    "NATIVE_VERIFICATION_SURFACE",
    "OPENTITAN_ADJUDICATION_SURFACE",
    "OPENTITAN_ADJUDICATION_SUMMARY_SURFACE",
    "OPENTITAN_ADJUDICATION_SUMMARY_VALIDATION_REPORT_SURFACE",
    "OPENTITAN_ADJUDICATION_VALIDATION_REPORT_SURFACE",
    "OPENTITAN_ADJUDICATION_RUN_SPEC_REPORT_SURFACE",
    "OPENTITAN_ADJUDICATION_RUN_SPEC_SURFACE",
    "OPENTITAN_EVIDENCE_BUNDLE_SURFACE",
    "OPENTITAN_EVIDENCE_SCHEMA_VERSION",
    "OPENTITAN_SEMANTIC_MANIFEST_SURFACE",
    "OPENTITAN_TARGET_CONTRACT_SURFACE",
    "OPENTITAN_TARGET_CONTRACT_REPORT_SURFACE",
    "RTL_BOUNDARY_ANALYSIS_SURFACE",
    "RTL_BOUNDARY_ADJUDICATION_SURFACE",
    "RTL_BOUNDARY_BENCHMARK_SCHEMA_VERSION",
    "RTL_BOUNDARY_EVIDENCE_BUNDLE_SURFACE",
    "RTL_BOUNDARY_EXPERIMENT_CONTRACT_SURFACE",
    "RTL_BOUNDARY_GROUND_TRUTH_SURFACE",
    "RTL_BOUNDARY_POLICY_ANALYSIS_SURFACE",
    "RTL_BOUNDARY_POLICY_TRIAL_SURFACE",
    "RTL_BOUNDARY_PIPELINE_RESULT_SURFACE",
    "RTL_BOUNDARY_PLOT_PAYLOAD_SURFACE",
    "RTL_BOUNDARY_REPORT_BUNDLE_SURFACE",
    "RTL_BOUNDARY_REPORT_VALIDATION_SURFACE",
    "RTL_BOUNDARY_SCHEMA_VERSION",
    "RTL_BOUNDARY_SWEEP_ENUMERATION_SURFACE",
    "RTL_BOUNDARY_SWEEP_SPACE_SURFACE",
    "RTL_BOUNDARY_SEMANTIC_MANIFEST_SURFACE",
    "BoundaryBenchmarkError",
    "NativeManifestError",
    "OpenTitanEvidenceError",
    "PhysicalProbeError",
    "CoverageMappingError",
    "EvalEffectError",
    "SidecarError",
    "SweepBoundaryError",
    "analyze_manifest",
    "analyze_boundary_ground_truth",
    "analyze_boundary_policy_trial",
    "adjudicate_boundary_benchmark",
    "adjudication_input_error",
    "adjudicate_external_evidence",
    "capture_manifest",
    "build_toggle_coverage_mapping",
    "build_boundary_report_bundle",
    "classify_eval_effects",
    "coverage_region_contracts",
    "extract_semantic_projection",
    "extract_native_eval_closure",
    "enumerate_sweep_space",
    "file_sha256",
    "probe_physical_layout",
    "project_native_checkpoint",
    "resolve_physical_bindings",
    "validate_layout_observation",
    "validate_coverage_mapping",
    "validate_effect_contract",
    "validate_eval_effects",
    "validate_manifest",
    "validate_native_checkpoint_manifest",
    "validate_native_manifest",
    "verify_adapter_semantics",
    "verify_native_adapter",
    "format_adjudication_report",
    "format_adjudication_summary_report",
    "format_output_validation_report",
    "format_target_contract_report",
    "read_strict_json_object",
    "reconstruct_boundary_prediction",
    "summarize_adjudications",
    "select_boundary_points",
    "validate_adjudication_document",
    "validate_adjudication_run_spec",
    "validate_adjudication_summary_document",
    "validate_boundary_report_bundle",
    "validate_target_contract_document",
    "write_manifest",
    "write_json_atomic",
    "write_layout_observation",
    "write_native_checkpoint",
    "write_native_verification",
    "write_eval_effects",
    "write_text_atomic",
]

__version__ = "0.1.0"
